name = "PhysLeanLatest"
defaultTargets = ["PhysLeanLatest"]
# -- Optional inclusion for LeanCopilot
#moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]

[[require]]
name = "PhysLean"
git = "https://github.com/HEPLean/PhysLean"
rev = "v4.17.0"
